### ISSUE TITLE
Unable to extract dates, times are inconsistent

### ISSUE THREAD

**Issue by hunbadco** [sedthh/lara-hungarian-nlp#1] opened 2018-06-12 18:18 UTC
No dates are getting extracted using the parser when they are defined relatively or using strings.

Lara version: current, 2018-06-12, master branch
Python version: 3.5.2

The example code returns the following result with no date and multiple wrong time values:
```
from lara import parser

sorcery		= 'Hívj fel ezen a számon 2018 IV. huszadikán mondjuk délután nyolc perccel háromnegyed kettő előtt!'
info		= parser.Extract(sorcery)
print(info.dates())
print(info.times())

>>> []
>>> ['20:00', '13:45']
```

Another example where the extracted time is correct, but again, I'm getting no date:
```
sorcery		= 'Hívj fel ezen a számon ma délután nyolc perccel háromnegyed kettő előtt!'

>>> []
>>> ['13:37']
```

A more simple example:
```
sorcery		= 'Holnap ötkor.'

>>> []
>>> ['17:00']
```

When specifying the date with numbers, the error seems to be gone:
```
sorcery		= 'Július harmincadikán reggel fél hatkor.'

>>> []
>>> ['05:30']

sorcery		= '07.30. reggel fél hatkor.'

>>> ['2018-07-30']
>>> ['05:30']
```

**Comment by sedthh** [comment] 2018-06-13 13:01
Thank you very much for reporting this issue in such detail.

The examples used to work in previous versions and haven't checked them since (forgot to add them to the unit tests and the rest of the tests all passed without any errors so I didn't notice).

There were 2 causes for this bug:
1) the Extract() class can turn numerals into actual integers and this function was altered in a way, that affixes after the numerals would remain in the strings (huszadikán -> 20án) which would cause some of the regular expressions to ignore certain matches
2) the Extract() functions were altered in a way that they would also accept strange, rather exotic date and time formats as well as possible matches, which has lead to matching parts of the reported time format multiple times, instead matching it as a whole (délután nyolc -> 20:00, háromnegyed kettő előtt -> 13:45)

The reported issues are fixed in the latest version and should now work as intended. Please let me know if there's another issue.

**Closed as completed by sedthh** 2018-06-13 13:01 UTC
